GET http://localhost:8080/worker/rest?depthLevel=0&flowType=WATERFALL&dataSize=3

###
POST http://localhost:8080/worker/rest
Content-Type: application/json

{
  "config": {
    "depthLevel": 3,
    "dataSize": 2,
    "flowType": "WATERFALL"
  },
  "data": [
    {
      "id": 1,
      "name": "name",
      "lastName": "lastname",
      "age": 22,
      "date": "2023-12-12",
      "height": 5.5
    },
    {
      "id": 2,
      "name": "name",
      "lastName": "lastname",
      "age": 25,
      "date": "2023-12-12",
      "height": 5.0
    },
    {
      "id": 3,
      "name": "name",
      "lastName": "lastname",
      "age": 32,
      "date": "2023-12-12",
      "height": 0.5
    },
    {
      "id": 4,
      "name": "name",
      "lastName": "lastname",
      "age": 2,
      "date": "2023-12-12",
      "height": 6.5
    }
  ]
}

###
GET http://localhost:8080/grpc/hello/Anton/Sheverda

###
GRPC localhost:9090/ru.itis.workernode.grpc.hello.HelloService/hello

{
  "firstName": "Dinar",
  "lastName": "Sheverda"
}

###
GRPC localhost:9090/ru.itis.workernode.grpc.WorkerGrpcService/testGetData

{
  "config": {
    "depthLevel": 4,
    "dataSize": 2,
    "flowType": "WATERFALL"
  },
  "data": []
}

###
GRPC localhost:9090/ru.itis.workernode.grpc.WorkerGrpcService/testPostData

{
  "config": {
    "depthLevel": 2,
    "dataSize": 2,
    "flowType": "WATERFALL"
  },
  "data": [
    {
      "id": 1,
      "name": "name",
      "lastName": "lastname",
      "age": 22,
      "date": "2023-12-12",
      "height": 5.5
    },
    {
      "id": 2,
      "name": "name",
      "lastName": "lastname",
      "age": 25,
      "date": "2023-12-12",
      "height": 5.0
    },
    {
      "id": 3,
      "name": "name",
      "lastName": "lastname",
      "age": 32,
      "date": "2023-12-12",
      "height": 0.5
    },
    {
      "id": 4,
      "name": "name",
      "lastName": "lastname",
      "age": 2,
      "date": "2023-12-12",
      "height": 6.5
    }
  ]
}

###
GET http://localhost:8080/grpc/hello/Anton/Sheverda